post_install()
{
  echo 'Add those environment variables to your .bashrc to use the symbian toolchain'
  echo 'export PATH=/opt/gnupoc1_15/bin:$PATH'
  echo 'export EPOCROOT=/opt/gnupoc1_15/symbian-sdks/5.0/'
}

post_remove()
{
  echo 'You can now remove those environment variables from your .bashrc'
  echo 'export PATH=/opt/gnupoc1_15/bin:$PATH'
  echo 'export EPOCROOT=/opt/gnupoc1_15/symbian-sdks/5.0/'
}
